### ISSUE TITLE
Actividad 6 - Animacion de objeto 3d

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-irving-1#1]
[Actividad 6 Animacion.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-realidad-aumentada-de-objeto-3d-con-animacion-equipo-irving-1/files/14706035/Actividad.6.Animacion.pdf)

**Comment by magaly1311** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado..
